name: blake2b
description: A dart implement of blake2b referenced from blacknet.
version: 0.1.2
author: riclava <riclavaz@gmail.com>
homepage: https://github.com/riclava/blake2b

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fixnum: ^0.10.9
  hex: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter